spring:
  application:
    name: microservice

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Aniks68/Spring-Cloud-Config-Server.git
#          /* TODO: switch URL to properties repo */


server:
  port: ${port:8888}